# Generated by Django 4.1.6 on 2023-02-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=255)),
                ('hotels_rating', models.IntegerField()),
                ('season', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('transport', models.CharField(max_length=250)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('free_places', models.IntegerField()),
                ('in_stock', models.BooleanField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PacketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='media/packet_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('udated_at', models.DateTimeField(auto_now=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Packets.packet')),
            ],
        ),
        migrations.AddField(
            model_name='packet',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='Packets.packetimage'),
        ),
    ]
