# Generated by Django 4.1.6 on 2023-02-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Packets', '0001_initial'),
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='packets_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='Reviews.comment'),
        ),
        migrations.AddField(
            model_name='packet',
            name='packets_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packetrating', to='Reviews.rating'),
        ),
    ]
